### ISSUE TITLE
Determinização de AFs

### ISSUE THREAD

**Issue by AdrianoTosetto** [AdrianoTosetto/Formal-Languages-and-Compilers-INE5421#5]

**Comment by ggsimao** [comment]
Quase funcionando. O programa não detecta quando dois estados são iguais, o que causa os seguintes problemas:

1. o estado λ não é um estado de aceitação no AFD resultante
2. há muitos estados adicionais com nomes repeditos, os quais não têm nenhuma transição

**Comment by AdrianoTosetto** [comment]
Está resolvido?
